<?php

namespace Ais\ProvinsiBundle\Repository;

/**
 * ProvinsiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinsiRepository extends \Doctrine\ORM\EntityRepository
{
}
